# -*- mode: ruby -*-

Vagrant.configure(2) do |config|
  config.vm.box = "globaleaks.box"
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.synced_folder "data", "/data/globaleaks"
  config.vm.provision "shell", path: "scripts/globaleaks.sh"
end
