#!/bin/sh
# This is the post installation script for globaleaks
set -e

if [ -d "/var/globaleaks" ]; then
  timestamp=$(date +%s)
  version=`dpkg -s globaleaks | grep '^Version:' | cut -d ' ' -f2`
  filepath=/var/globaleaks/backups/globaleaks-$version-$timestamp.tar.gz
  echo "Creating backup of /var/globaleaks in $filepath"
  mkdir -p /var/globaleaks/backups
  chown globaleaks:globaleaks /var/globaleaks/backups
  tar --exclude='/var/globaleaks/backups' -zcvf $filepath /var/globaleaks
fi
