#!/bin/bash
#        .;''-.
#      .' |    `._
#     /`  ;       `'.
#   .'     \         \
#  ,'\|    `|         |
#  | -'_     \ `'.__,J
# ;'   `.     `'.__.'
# |      `"-.___ ,'
# '-,           /
# |.-`-.______-|
# }      __.--'L
# ;   _,-  _.-"`\         ___
# `7-;"   '  _,,--._  ,-'`__ `.
#  |/      ,'-     .7'.-"--.7 |        _.-'
#  ;     ,'      .' .'  .-. \/       .'
#   ;   /       / .'.-     ` |__   .'
#    \ |      .' /  |    \_)-   `'/   _.-'``
#     _,.--../ .'     \_) '`_      \'`
#   '`f-'``'.`\;;'    ''`  '-`      |
#      \`.__. ;;;,   )              /
#       `-._,|;;;,, /\            ,'
#        / /<_;;;;'   `-._    _,-'
#       | '- /;;;;;,      `t'` \. I like nonsence.
#       `'-'`_.|,';;;,      '._/| It wakes up the brain cells!
#       ,_.-'  \ |;;;;;    `-._/
#             / `;\ |;;;,  `"     - Theodor Seuss Geisel -
#           .'     `'`\;;, /
#          '           ;;;'|
#              .--.    ;.:`\    _.--,
#             |    `'./;' _ '_.'     |
#              \_     `"7f `)       /
#              |`   _.-'`t-'`"-.,__.'
#              `'-'`/;;  | |   \ mx
#                  ;;;  ,' |    `
#                      /   '

cat ${BASH_SOURCE[0]} | head -n 36 | tail -n 35

echo
echo "[+] Sorry to hear you did not enjoy your leaking experience"
echo "    send us an email to info@globaleaks.org"


if [ "$1" = "purge" ]; then
  echo "Forcefully purging all globaleaks data except /var/globaleaks/torhs directory"
  rm -rf /var/globaleaks/db
  rm -rf /var/globaleaks/files
  rm -rf /var/globaleaks/log
  rm -rf /var/run/globaleaks
fi

#DEBHELPER#

exit 0
