#!/bin/sh
# This is the post installation script for globaleaks
id globaleaks
if [ $? -ne 0 ]; then
  useradd globaleaks -u 1337
fi
if [ ! -d /var/globaleaks ]; then
  mkdir /var/globaleaks/
fi
chown globaleaks:globaleaks /var/globaleaks
echo "[+] Compiling python files"
for path in `python -c "import sys;print '\n'.join(sys.path)"`;do
  python -mcompileall $path
done
### Bellow here things will be added by the build script

