#!/bin/sh
# This is the pre installation script for globaleaks

lsb_release -c | grep precise >/dev/null 2>&-
if [ "$?" -ne "0" ]; then
    echo "WARNING! Currently GlobaLeaks offers only Ubuntu 12.04 (precise) support"
fi

#DEBHELPER#

exit 0
