#!/bin/bash
CWD=`pwd`
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPTNAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
GLBACKEND_GIT_REPO="https://github.com/globaleaks/GLBackend.git"
GLCLIENT_GIT_REPO="https://github.com/globaleaks/GLClient.git"
GLOBALEAKS_DIR=~/
OUTPUT_DIR=/data/website/builds/

if [ "$1" -eq '-h' ]; then
  echo "Usage: ./${SCRIPTNAME} (optional) [glclient target tag or rev] [glbackend target tag]"
  echo "repository path: is the path to a copy of the GLClient and GLBackend git repositories"
  exit
fi

if [ "$#" -eq 2 ]; then
  GLCLIENT_TAG=$1
  GLBACKEND_TAG=$2
fi

mkdir $OUTPUT_DIR/GLClient
mkdir $OUTPUT_DIR/GLBackend

if [ ! -d ${GLOBALEAKS_DIR}/GLBackend ]; then
  echo "[+] Cloning GLBackend in ${GLOBALEAKS_DIR}"
  git clone $GLBACKEND_GIT_REPO ${GLOBALEAKS_DIR}/GLBackend
fi

if [ ! -d ${GLOBALEAKS_DIR}/GLClient ]; then
  echo "[+] Cloning GLClient in ${GLOBALEAKS_DIR}"
  git clone $GLCLIENT_GIT_REPO ${GLOBALEAKS_DIR}/GLClient
fi

echo "[+] Updating GLBackend"
cd ${GLOBALEAKS_DIR}/GLBackend
git pull origin master
GLBACKEND_REVISION=`git rev-parse HEAD | cut -c 1-8`

if test $GLBACKEND_TAG; then
  git checkout $GLBACKEND_TAG
  $GLBACKEND_REVISION=$GLBACKEND_TAG
fi

echo "[+] Updating GLClient"
cd ${GLOBALEAKS_DIR}/GLClient
git pull origin master
GLCLIENT_REVISION=`git rev-parse HEAD | cut -c 1-8`

if test $GLCLIENT_TAG; then
  git checkout $GLCLIENT_TAG
  $GLCLIENT_REVISION=$GLCLIENT_TAG
fi

echo "[+] Building GLClient"
npm install -d
grunt build

echo "[+] Creating compressed archives"
mv build glclient-${GLCLIENT_REVISION}
tar czf glclient-${GLCLIENT_REVISION}.tar.gz glclient-${GLCLIENT_REVISION}/
md5sum glclient-${GLCLIENT_REVISION}.tar.gz > $OUTPUT_DIR/GLClient/glclient-${GLCLIENT_REVISION}.tar.gz.md5.txt
sha1sum glclient-${GLCLIENT_REVISION}.tar.gz > $OUTPUT_DIR/GLClient/glclient-${GLCLIENT_REVISION}.tar.gz.sha1.txt
shasum -a 224 glclient-${GLCLIENT_REVISION}.tar.gz > $OUTPUT_DIR/GLClient/glclient-${GLCLIENT_REVISION}.tar.gz.sha224.txt

zip -r glclient-${GLCLIENT_REVISION}.zip glclient-${GLCLIENT_REVISION}/
md5sum glclient-${GLCLIENT_REVISION}.zip > $OUTPUT_DIR/GLClient/glclient-${GLCLIENT_REVISION}.zip.md5.txt
sha1sum glclient-${GLCLIENT_REVISION}.zip > $OUTPUT_DIR/GLClient/glclient-${GLCLIENT_REVISION}.zip.sha1.txt
shasum -a 224 glclient-${GLCLIENT_REVISION}.zip > $OUTPUT_DIR/GLClient/glclient-${GLCLIENT_REVISION}.zip.sha224.txt

mv glclient-${GLCLIENT_REVISION}.tar.gz $OUTPUT_DIR/GLClient
mv glclient-${GLCLIENT_REVISION}.zip $OUTPUT_DIR/GLClient
rm -rf glclient-${GLCLIENT_REVISION}
cd $CWD

echo "[+] Building GLBackend"
cd ${GLOBALEAKS_DIR}/GLBackend
POSTINST=${GLOBALEAKS_DIR}/GLBackend/debian/postinst
echo -n "pip install " >> $POSTINST
for require in `cat ${GLOBALEAKS_DIR}/GLBackend/requirements.txt`; do
  echo -n "${require} " >> $POSTINST
done
echo "" >> $POSTINST
echo "/etc/init.d/globaleaks start" >> $POSTINST
echo "# generated by your friendly globaleaks build bot :)" >> $POSTINST
python setup.py sdist
echo "[+] Building .deb"

cd dist
py2dsc globaleaks-0.2.tar.gz
cd deb_dist/globaleaks-0.2
rm -rf debian/
cp -rf ${GLOBALEAKS_DIR}/GLBackend/debian debian
debuild
cd ..
echo "[+] Adding to local repository"
dput local globaleaks*changes
mini-dinstall --batch
cd $CWD

echo "[+] Signing Release"
$DIR/sign-release.sh

echo "[+] All done!"

