#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. ${DIR}/common_inc.sh

usage()
{
cat << EOF
usage: ./${SCRIPTNAME} options

OPTIONS:
   -h      Show this message
   -v      To build a tagged release
   -n      To build a non signed package

EOF
}

SIGN=1
while getopts “hv:n” OPTION
do
  case $OPTION in
    h)
      usage
      exit 1
      ;;
    v)
      TAG=$OPTARG
      ;;
    n)
      SIGN=0
      ;;
    ?)
      usage
      exit
      ;;
    esac
done

build_glbackend()
{
  cd ${BUILD_DIR}
  BUILD_USES_EXISTENT_DIR=0
  if [ -d ${GLBACKEND_DIR} ]; then
    echo "Directory ${GLBACKEND_DIR} already present"
    echo "The build process needs a clean git clone of GLBackend"
    echo "If not deleted the build script will use the existent dir"
    read -n1 -p "Do you want to delete ${GLBACKEND_DIR}? (y/n): "
    echo
    if [[ $REPLY == [yY] ]]; then
      echo "Removing directory ${GLBACKEND_DIR}"
      rm -rf ${GLBACKEND_DIR}
    else
      BUILD_USES_EXISTENT_DIR=1
      cd ${GLBACKEND_DIR}
    fi
  fi

  if [ ${BUILD_USES_EXISTENT_DIR} -eq 0 ]; then
    echo "[+] Cloning GLBackend in ${GLBACKEND_DIR}"
    git clone $GLBACKEND_GIT_REPO ${GLBACKEND_DIR}
    cd ${GLBACKEND_DIR}
    if test $GLBACKEND_TAG; then
      git checkout $GLBACKEND_TAG
      GLBACKEND_REVISION=$GLBACKEND_TAG
    else
      GLBACKEND_REVISION=`git rev-parse HEAD | cut -c 1-8`
    fi
  fi

  unzip ${GLC_BUILD}/*.zip -d ${GLBACKEND_DIR}
  mv ${GLBACKEND_DIR}/glclient* ${GLBACKEND_DIR}/glclient

  echo "[+] Building GLBackend"
  POSTINST=${GLBACKEND_DIR}/debian/postinst
  echo "/etc/init.d/globaleaks start" >> $POSTINST
  echo "# generated by your friendly globaleaks build bot :)" >> $POSTINST
  python setup.py sdist
  echo "[+] Building .deb"

  cd dist
  py2dsc globaleaks-*.tar.gz
  cd deb_dist/globaleaks-*
  rm -rf debian/
  cp -rf ${GLBACKEND_DIR}/debian debian

  if [ $SIGN -eq 1 ]; then
    debuild
  else
    debuild -i -us -uc -b
  fi

  rm -rf ${GLB_BUILD}
  mv ${GLBACKEND_DIR}/dist ${GLB_BUILD}
}

build_glbackend

echo "[+] All done!"

