#!/bin/bash

if [ ! $GLCLIENT_INSTALL_DIR ];then
  GLCLIENT_INSTALL_DIR=/var/globaleaks/custom-glclient
fi

usage()
{
cat << EOF
usage: ./build-custom-glclient.sh options

OPTIONS:
    -h                         Show this message
    -r                         Restore to default GLClient installation
    -p <path to custom-gl>     Build custom GLCLient version
    -i                         Install GLClient dependencies
EOF
}

get_sudo()
{
  echo "[+] Let's sudo now, so we don't nag you forever later..."
  command -v sudo >/dev/null 2>&1 || {
    echo "[!] sudo is not installed. No point to continue..."
    exit 2
  }
  sudo echo "Thanks :)"
}

restore_default_glclient()
{
  echo "[+] Restoring to default GLClient... "
  rm -rf $GLCLIENT_INSTALL_DIR
  echo "[*] Restored."
}

install_glclient_dependencies()
{
  echo "[+] Installing development dependencies... "
  sudo apt-get install git -y
  sudo add-apt-repository ppa:chris-lea/node.js -y
  sudo apt-get update -y
  sudo apt-get install nodejs -y
  sudo npm install -g grunt-cli bower
}

build_custom_glclient()
{
  ( command -v git >/dev/null 2>&1 &&
    command -v node >/dev/null 2>&1 &&
    command -v npm >/dev/null 2>&1 &&
    command -v bower >/dev/null 2>&1 &&
    command -v grunt >/dev/null 2>&1) || {
    RELEASE="`lsb_release -c|cut -f 2`"
    if [ $RELEASE != "precise" ]; then
      echo "[+] You are not running Ubuntu 12.04 LTS"
      echo "[!] You must install node on your own."
      echo "See: https://github.com/joyent/node/wiki/Installation"
      exit 1
    fi
    echo "[+] Node JS does not appear to be installed."
    while true; do
      read -p "Should we install them? (y|n) " yn
      case $yn in
          [Yy]* ) install_glclient_dependencies; break;;
          [Nn]* ) usage; exit;;
          * ) echo "I only understand yes or no, what do you want from me?";;
      esac
    done
  }

  TMP_DIR=`mktemp -d /tmp/GLClient_tmp.XXXXXXX`
  INDEX_FILE=$TMP_DIR/GLCLient/app/index.html
  echo "[+] Building custom GLClient using: ${CUSTOM_GLCLIENT_DIR}... "
  echo "[+] Cloning latest GLCLient version... "
  CWD=`pwd`
  git clone https://github.com/globaleaks/GLClient.git $TMP_DIR/GLCLient
  cd $TMP_DIR/GLCLient
  echo "[+] Checking out ${GLCLIENT_TAG} revision"
  git checkout $GLCLIENT_TAG
  cd $CWD

  cp -R $CUSTOM_GLCLIENT_DIR/* $TMP_DIR/GLCLient/app/

  cd $TMP_DIR/GLCLient
  npm install -d
  bower update -f
  grunt build

  echo "[+] Cleaning up currently installed custom build... "
  sudo rm -rf $GLCLIENT_INSTALL_DIR

  sudo mv build $GLCLIENT_INSTALL_DIR
  #rm -rf $TMP_DIR
}

if [ ! $1 ];then
  usage
fi

if [[ $EUID -eq 0 ]]; then
  echo "!! This script must not be run as root. Please execute it as a normal user with sudo!"
  usage
  exit 1
fi

while getopts "hrp:v:i" OPTION
do
  case $OPTION in
    h)
      usage
      exit 1
      ;;
    r)
      restore_default_glclient
      exit 0
      ;;
    p)
      if [ ! $2 ];then
        echo "[!] Missing custom-gl path."
        usage
        exit 1
      fi

      CUSTOM_GLCLIENT_DIR=$2
      ;;
    v)
      GLCLIENT_TAG=$OPTARG
      ;;
    i)
      get_sudo
      install_glclient_dependencies
      ;;
    ?)
      usage
      exit 1
      ;;
  esac
done

if [ ! $GLCLIENT_TAG ];then
  GLCLIENT_TAG="v"`python -c 'import globaleaks;print globaleaks.__version__'`
fi

get_sudo
build_custom_glclient
