#!/bin/bash

if [ ! $GLCLIENT_INSTALL_DIR ];then
  GLCLIENT_INSTALL_DIR=/var/globaleaks/custom-glclient
fi

usage()
{
cat << EOF
usage: ./build-custom-glclient.sh options

OPTIONS:
    -h                                Show this message
    -i                                Install GLClient dependencies
    -b <path to custom-gl> [-v tag ]  Build custom GLCLient version
    -d <path to custom-gl-build>      Deploy custom GLClient version
    -r                                Restore to default GLClient installation
EOF
}

get_sudo()
{
  echo "[+] Let's sudo now, so we don't nag you forever later..."
  command -v sudo >/dev/null 2>&1 || {
    echo "[!] sudo is not installed. No point to continue..."
    exit 2
  }
  sudo echo "Thanks :)"
}

restore_default_glclient()
{
  echo "[+] Restoring to default GLClient... "
  rm -rf $GLCLIENT_INSTALL_DIR
  echo "[*] Restored."
}

install_glclient_dependencies()
{
  echo "[+] Installing development dependencies... "
  sudo apt-get install git -y
  sudo add-apt-repository ppa:chris-lea/node.js -y
  sudo apt-get update -y
  sudo apt-get install nodejs -y
  sudo npm install -g grunt-cli bower
}

build_custom_glclient()
{
  ( command -v git >/dev/null 2>&1 &&
    command -v node >/dev/null 2>&1 &&
    command -v npm >/dev/null 2>&1 &&
    command -v bower >/dev/null 2>&1 &&
    command -v grunt >/dev/null 2>&1) || {
    RELEASE="`lsb_release -c|cut -f 2`"
    if [ $RELEASE != "precise" ]; then
      echo "[+] You are not running Ubuntu 12.04 LTS"
      echo "[!] You must install node on your own."
      echo "See: https://github.com/joyent/node/wiki/Installation"
      exit 1
    fi
    echo "[+] Node JS does not appear to be installed."
    while true; do
      read -p "Should we install them? (y|n) " yn
      case $yn in
          [Yy]* ) install_glclient_dependencies; break;;
          [Nn]* ) usage; exit;;
          * ) echo "I only understand yes or no, what do you want from me?";;
      esac
    done
  }

  TMP_DIR=`mktemp -d /tmp/GLClient_tmp.XXXXXXX`
  INDEX_FILE=$TMP_DIR/GLCLient/app/index.html
  echo "[+] Building custom GLClient using: ${CUSTOM_GLCLIENT_DIR}... "
  echo "[+] Cloning latest GLCLient version... "
  CWD=`pwd`
  git clone https://github.com/globaleaks/GLClient.git $TMP_DIR/GLCLient
  cd $TMP_DIR/GLCLient
  echo "[+] Checking out ${GLCLIENT_TAG} revision"
  git checkout $GLCLIENT_TAG
  cd $CWD

  cp -R $CUSTOM_GLCLIENT_DIR/* $TMP_DIR/GLCLient/app/

  cd $TMP_DIR/GLCLient
  npm install -d
  bower update -f
  grunt build
}

deploy_custom_glclient()
{
  echo "[+] Cleaning up currently installed custom build... "
  sudo rm -rf $GLCLIENT_INSTALL_DIR

  sudo cp -r CUSTOM_GLCLIENT_BUILD_DIR $GLCLIENT_$GLCLIENT_INSTALL_DIR
}

if [[ $EUID -eq 0 ]]; then
  echo "!! This script must not be run as root. Please execute it as a normal user with sudo!"
  usage
  exit 1
fi

COUNTER=0

while getopts "hrp:d:v:i" OPTION
do
  case $OPTION in
    h)
      usage
      exit 1
      ;;
    r)
      COUNTER=$((COUNTER+1))
      RESTORE=1
      exit 0
      ;;
    p)
      COUNTER=$((COUNTER+1))

      if [ ! $2 ];then
        echo "[!] Missing custom-gl path."
        usage
        exit 1
      fi

      CUSTOM_GLCLIENT_DIR=$2
      BUILD=1
      ;;
    d)
      COUNTER=$((COUNTER+1))

      if [ ! $2 ];then
        echo "[!] Missing custom-gl-build path."
        usage
        exit 1
      fi

      CUSTOM_GLCLIENT_BUILD_DIR=$2
      DEPLOY=1
      ;;
    v)
      COUNTER=$((COUNTER+1))
      GLCLIENT_TAG=$OPTARG
      ;;
    i)
      COUNTER=$((COUNTER+1))
      INSTALLDEP=1
      ;;
    ?)
      usage
      exit 1
      ;;
  esac
done

if [ ! $GLCLIENT_TAG ]; then
  GLCLIENT_TAG="master"
fi

echo $COUNTER
if [ $COUNTER != 1 ]; then
  usage
  exit 1
fi

get_sudo

if [ $RESTORE ]; then
  restore_default_glclient
fi

if [ $INSTALLDEP ]; then
  install_glclient_dependencies
fi

if [ $BUILD ]; then
  build_custom_glclient
fi

if [ $DEPLOY ]; then
  deploy_custom_glclient
fi 
